name: afterworld_bar_app
description: AfterWorld Bar – POS mit Accounts, PIN, Rechten, CSV-Import, Bereichssperre & Pfand
publish_to: "none"
version: 0.3.0+3

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.19.0
  file_picker: ^8.0.3
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
 uses-material-design: true
  assets:
    - assets/images/aw_skull.png
    - assets/images/aw_bg_pattern.png  
