name: afterworld_bar_app
description: AFTERWORLD • Bar Kasse
publish_to: "none"
version: 0.3.0+3

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.19.0
  file_picker: ^8.0.3
  csv: ^6.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/aw_skull.png
    - assets/images/aw_bg_pattern.png

flutter_icons:
  android: true
  ios: false
  image_path: assets/images/aw_skull.png
  adaptive_icon_background: "#F4EFE8"
  adaptive_icon_foreground: assets/images/aw_skull.png

flutter_native_splash:
  color: "#F4EFE8"
  image: assets/images/aw_skull.png
  android: true
  android_12:
    color: "#F4EFE8"
    image: assets/images/aw_skull.png
