name: afterworld_bar
description: AfterWorld Bar – POS/Kassensystem für Bar, Schankwagen & VIP
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  intl: ^0.18.1
  google_fonts: ^6.2.1
  file_picker: ^6.1.1
  csv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/      # z.B. assets/images/aw_skull.png (Login-Logo)
    - assets/splash/      # z.B. assets/splash/aw_splash.png (Splash-Logo)

# App-Icon (Generator wird nur ausgeführt, wenn du den Befehl startest)
flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icons/aw_icon.png
  adaptive_icon_background: "#1B1B1F"                   # AWBrand.skullBlack
  adaptive_icon_foreground: assets/icons/aw_icon_adaptive_fore.png
  adaptive_icon_monochrome: assets/icons/aw_icon_monochrome.png

# Splashscreen (wird beim Befehl generiert)
flutter_native_splash:
  color: "#1B1B1F"                                      # dunkler Hintergrund
  image: assets/splash/aw_splash.png
  android_12:
    color: "#1B1B1F"
    image: assets/splash/aw_splash.png
