name: Build Android APK (Flutter)

on:
  workflow_dispatch: {}   # Manuell starten über "Actions → Run workflow"
  # push:
  #   branches: [ "main" ]  # Optional: bei jedem Push bauen

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          # flutter-version: "3.22.2"  # Optional: fixieren

      - name: Flutter doctor
        run: flutter doctor -v

      # Nur falls android/ im Repo fehlt (z. B. nur lib/ gepusht)
      - name: Ensure Android platform exists
        run: |
          if [ ! -d "android" ]; then
            flutter create --platforms=android .
          fi

      # Löscht den Default-Test, den "flutter create" ggf. erzeugt
      - name: Remove default test (created by flutter create)
        run: |
          if [ -f test/widget_test.dart ]; then
            rm -f test/widget_test.dart
          fi

      - name: List workspace (debug)
        run: |
          ls -la
          ls -la assets || true
          ls -la assets/images || true
          ls -la assets/splash || true

      - name: Pub upgrade (fix v1 embedding plugins) + clean
        run: |
          flutter pub upgrade --major-versions
          flutter clean

      - name: Pub get (verbose)
        run: flutter pub get -v

      # Optional-Generatoren: laufen nur, wenn die Dateien existieren
      - name: Generate launcher icon
        run: |
          if [ -f assets/icons/aw_icon.png ]; then
            dart run flutter_launcher_icons
          else
            echo "No assets/icons/aw_icon.png – skipping icons"
          fi

      - name: Generate native splash
        run: |
          if [ -f assets/splash/aw_splash.png ]; then
            dart run flutter_native_splash:create
          else
            echo "No assets/splash/aw_splash.png – skipping splash"
          fi

      # Analyzer so einstellen, dass Infos/Warnings nicht den Build stoppen
      - name: Analyze (nur echte Fehler)
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Build debug APK (verbose)
        run: flutter build apk --debug -v

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
