name: Build APK (Debug)

on:
  workflow_dispatch:
  push:
    paths:
      - 'pubspec.yaml'
      - 'lib/**.dart'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # WICHTIG: Android-/iOS-/Web-Ordner erzeugen (mind. Android)
      - name: Create Android project (if missing)
        run: flutter create . --platforms=android -t app

      - name: Pub get
        run: flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
