name: Build Android APK (Flutter)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          # flutter-version: "3.22.2" # optional fixieren

      - name: Flutter doctor
        run: flutter doctor -v

      # Falls android/ fehlt (z. B. nur lib/ gepusht)
      - name: Ensure Android platform exists
        run: |
          if [ ! -d "android" ]; then
            flutter create --platforms=android .
          fi

      - name: Pub get
        run: flutter pub get

      # Optional: Icon & Splash generieren (nur wenn Dateien existieren)
      - name: Generate launcher icon
        run: |
          if [ -f assets/icons/aw_icon.png ]; then
            dart run flutter_launcher_icons
          else
            echo "No assets/icons/aw_icon.png – skipping icons"
          fi
      - name: Generate native splash
        run: |
          if [ -f assets/splash/aw_splash.png ]; then
            dart run flutter_native_splash:create
          else
            echo "No assets/splash/aw_splash.png – skipping splash"
          fi

      - name: Build debug APK (verbose)
        run: flutter build apk --debug -v

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
