name: Build APK (Debug)

on:
  workflow_dispatch:
  push:
    paths:
      - 'pubspec.yaml'
      - 'lib/**.dart'
      - 'assets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Falls android/-Projekt noch nicht im Repo ist:
      - name: Create Android project (if missing)
        run: flutter create . --platforms=android -t app

      - name: Pub get
        run: flutter pub get

      # NEU: Launcher-Icons & Splash aus assets erzeugen
      - name: Generate launcher icons
        run: flutter pub run flutter_launcher_icons

      - name: Generate native splash
        run: flutter pub run flutter_native_splash:create

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
