name: Build Android APK (Flutter)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          # flutter-version: "3.22.2"

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Ensure Android platform exists
        run: |
          if [ ! -d "android" ]; then
            flutter create --platforms=android .
          fi

- name: Remove default test (created by flutter create)
  run: rm -f test/widget_test.dart


      - name: List workspace (debug)
        run: |
          ls -la
          ls -la assets || true
          ls -la assets/images || true
          ls -la assets/splash || true

      - name: Pub get (verbose)
        run: flutter pub get -v

      # Nur generieren, wenn Dateien existieren
      - name: Generate launcher icon
        run: |
          if [ -f assets/icons/aw_icon.png ]; then
            dart run flutter_launcher_icons
          else
            echo "No assets/icons/aw_icon.png – skipping icons"
          fi
      - name: Generate native splash
        run: |
          if [ -f assets/splash/aw_splash.png ]; then
            dart run flutter_native_splash:create
          else
            echo "No assets/splash/aw_splash.png – skipping splash"
          fi

      - name: Analyze (zeigt Syntax-/Imports-Fehler)
        run: flutter analyze

      - name: Build debug APK (verbose)
        run: flutter build apk --debug -v

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
