name: Build Android APK (Flutter)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Java 17 ist Pflicht für aktuelle Android/Gradle-Plugins
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # Android SDK + Lizenzen
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      # Flutter installieren
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          # optional festpinnen:
          # flutter-version: "3.22.2"

      - name: Flutter doctor
        run: flutter doctor -v

      # Falls jemand das Android-Verzeichnis gelöscht hat, hier neu erzeugen
      - name: Ensure Android platform exists
        run: |
          if [ ! -d "android" ]; then
            flutter create --platforms=android .
          fi

      - name: Pub get
        run: flutter pub get

      # Optional: Splash/Icon-Generatoren (nur wenn NICHT eingecheckt)
      # - run: dart run flutter_native_splash:create
      # - run: dart run flutter_launcher_icons

      # Für erste Tests lieber DEBUG bauen (keine Release-Keystore nötig)
      - name: Build debug APK (verbose)
        run: flutter build apk --debug -v

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
